services:
  ros2-humble:
    build: .
    container_name: ros2-humble-gazebo-fortress
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/mir_robot:/ws/mir_robot

    network_mode: "host"   
    stdin_open: true      
    tty: true             
